apiVersion: v1
kind: Service
metadata:
  name: notes-service
spec:
  type: NodePort
  selector:
    app: notes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30036

