# rbac/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: notes-app-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]

