# rbac/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: notes-app-rb
  namespace: default
subjects:
  - kind: ServiceAccount
    name: notes-app-sa
    namespace: default
roleRef:
  kind: Role
  name: notes-app-role
  apiGroup: rbac.authorization.k8s.io

